### ISSUE TITLE
Opacity

### ISSUE THREAD

**Issue by Mattio-cmd** [meliora-theme/neovim#4]
I think that changing the opacity is not available right now. So i think it would be really cool if it did.

**Comment by ramojus** [comment]
Do you mean an option for transparent background? I think the specific opacity is controlled by the terminal, not neovim. I could try to implement this a bit later, maybe within this week.

**Comment by Mattio-cmd** [comment]
> 

Yes, exactly that. I'm using st and also double checked my Xresourcess, even tough i have them both set to 0.92 opacity background, it does not affect nvim with this specific colorscheme.
